application: sellweek-testing
version: 8
runtime: go
api_version: go1

handlers:
- url: /admin.*
  script: _go_app
  login: admin
  auth_fail_action: redirect
- url: /api/presentation/.*/description
  script: _go_app
  login: admin
  auth_fail_action: unauthorized
- url: /api/presentation/.*/name
  script: _go_app
  login: admin
  auth_fail_action: unauthorized
- url: /api/presentation/activate
  script: _go_app
  login: admin
- url: /favicon.ico
  static_files: templates/static/images/favicon.ico
  upload: templates/static/images/favicon.ico
- url: /static
  static_dir: templates/static
- url: /.*
  script: _go_app