application: togpm5
version: 4
runtime: go
api_version: go1

handlers:
- url: /admin.*
  script: _go_app
  login: admin
  auth_fail_action: redirect
- url: /favicon.ico
  static_files: templates/static/favicon.ico
  upload: templates/static/favicon.ico
- url: /static
  static_dir: templates/static
- url: /.*
  script: _go_app